export const defaultWords = [
    { id: 0, enWord: "book", ukWord: "книга" },
    { id: 1, enWord: "table", ukWord: "стол" },
    { id: 2, enWord: "chair", ukWord: "стул" },
    { id: 3, enWord: "car", ukWord: "автомобиль" },
    { id: 4, enWord: "dog", ukWord: "собака" },
    { id: 5, enWord: "cat", ukWord: "кот" },
    { id: 6, enWord: "house", ukWord: "дом" },
    { id: 7, enWord: "tree", ukWord: "дерево" },
    { id: 8, enWord: "sun", ukWord: "солнце" },
    { id: 9, enWord: "moon", ukWord: "луна" },
    { id: 10, enWord: "man", ukWord: "мужчина" },
    { id: 11, enWord: "woman", ukWord: "женщина" },
    { id: 12, enWord: "child", ukWord: "ребенок" },
    { id: 13, enWord: "day", ukWord: "день" },
    { id: 14, enWord: "night", ukWord: "ночь" },
    { id: 15, enWord: "door", ukWord: "дверь" },
    { id: 16, enWord: "window", ukWord: "окно" },
    { id: 17, enWord: "computer", ukWord: "компьютер" },
    { id: 18, enWord: "phone", ukWord: "телефон" },
    { id: 19, enWord: "friend", ukWord: "друг" },
];
